### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by JumperOnJava** [PieKing1215/InvMove#13]
Log here https://paste.ee/p/dwvIP

**Comment by PieKing1215** [comment]
The mod actually also requires [Fabric API](https://modrinth.com/mod/fabric-api) on Fabric, I still need to update the mod pages to say that but I fixed it in newer dev versions so it'll at least have a better error message.

**Comment by PieKing1215** [comment]
Closing this since I've updated all the mod pages to say they require Fabric API and added it a dependency so it'll give a better error message when loading if it's absent.
