### ISSUE TITLE
InvMove making JEI invisible because of Rubidium Extras (1.18.2)

### ISSUE THREAD

**Issue by Avaloneon23** [PieKing1215/InvMove#17]
![2022-08-09_20 34 34](https://user-images.githubusercontent.com/80372870/183648674-37347cbc-a8a2-463b-a651-435895bacc33.png)
This is what is shown when I try using InvMove one 1.18.2 Using Rubidium Extras.

**Comment by PieKing1215** [comment]
Does this only happen with InvMove? 
From what I'm seeing Rubidium Extras adds a "feature" that hides JEI's item list until you search: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26

**Comment by PieKing1215** [comment]
Closing because the problem seems to have nothing to do with InvMove and has since been fixed on their end.
