### ISSUE TITLE
Problem with Freecam

### ISSUE THREAD

**Issue by PieKing1215** [PieKing1215/InvMove#19]
https://modrinth.com/mod/freecam

When in freecam mode your actual player isn't supposed to move, but when an inventory is open both the camera and player move.

**Comment by Rozbiynk** [comment]
have same problem on tweakeroo's freecam

**Comment by PieKing1215** [comment]
Ok, in 5c3fcb3 I was able to make it so in this situation, neither the player nor camera move.
I tested with Freecam and Tweakeroo but it should also work for other mods that override the player input.

Making it so the camera can move but not the player would be something for InvMoveCompats since it would need to be special-cased per-mod.
