### ISSUE TITLE
Recipe book

### ISSUE THREAD

**Issue by GalaxysWithFiles** [PieKing1215/InvMove#2]
**Describe the bug**
Whenever you click the recipe book, whenever you jump it opens and closes it over and over

**To Reproduce**
click recipe book then jump

**Version and Mod List**
List the version of InvMove, the version of Fabric Loader+API, and the version of Minecraft the issue happens on:
InvMove: 0.1.1
Fabric Loader: (dont feel like checking sorry)
Fabric API: 0.46
Minecraft: 1.18.1

**Comment by PieKing1215** [comment]
Fixed for next release!
