### ISSUE TITLE
Quick Villager Trading Broken :(

### ISSUE THREAD

**Issue by jack-schultz** [PieKing1215/InvMove#20]
**Describe the bug**
When in a villager menu shift space clicking emeralds out of the trade menu doesn't work. My character jumps which is expected but in versions before 1.19 the menu would work as expected as well. 

**To Reproduce**
Basically the feature showcased in this video isn't working.
https://www.youtube.com/watch?v=LKV-pGVrBVs

**Version and Mod List**
Fabric InvMove-1.19-0.8.1-Fabric
version 1.19.2

List any other mods being used: 
All the other mods i am using are client-side
Image listing them all:
https://cdn.discordapp.com/attachments/873866021356830740/1028205213615652905/unknown.png

Thanks!

**Comment by PieKing1215** [comment]
Interesting, I'll take a look next time I work on an update.

**Comment by PieKing1215** [comment]
Fixed for next release!
