### ISSUE TITLE
Can't register items at personal crafting while moving forward (pressing W)

### ISSUE THREAD

**Issue by Psychodeus** [PieKing1215/InvMove#22]
## Describe the bug
When I move forward (Key W) while running or not, I can't pick any items to put somewhere in the slot, it always directed to personal crafting slot (The 4 square slots). And if I move sideward (Key A, D) it's completely normal.

## Crash Log
[latest.log](https://github.com/PieKing1215/InvMove/files/9845095/latest.log)

## My keybind
[options.txt](https://github.com/PieKing1215/InvMove/files/9845098/options.txt)

## Version and Mod List
List the version of InvMove, the version of Forge/Fabric/Quilt, and the version of Minecraft the issue happens on:
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer
Mod version: 0.8.1

## List any other mods being used:
![image](https://user-images.githubusercontent.com/93028949/197358037-a9434bb7-8803-439c-bc97-69faf0f9c4e3.png)

**Comment by PieKing1215** [comment]
Usually this is caused by having a mod that adds W+click as a "move to crafting grid" shortcut, though I didn't see any of the usual suspects in your list looking through quickly. I'll take a closer look later if that doesn't ring any bells

**Comment by Psychodeus** [comment]
![2022-10-23_04 21 16](https://user-images.githubusercontent.com/93028949/197360960-2c161a71-913b-485e-8edf-8df57bac4008.png)

It was Item scroller mod indeed it comes by default, now works fine :) Thanks!
