### ISSUE TITLE
Crash when launching minecraft

### ISSUE THREAD

**Issue by Willem07** [PieKing1215/InvMove#29]
Please explain the error
[latest.log](https://github.com/PieKing1215/InvMove/files/11083095/latest.log)

minecraft: 1.19.2-forge-43.2.7
mod version: InvMove-1.19-0.8.3-Forge

[Mod List.txt](https://github.com/PieKing1215/InvMove/files/11083179/Mod.List.txt)

**Comment by PieKing1215** [comment]
Hi! If you could try to narrow down the mod list to just a few that cause the problem that would be very helpful. There's not much to work with in the log.

**Comment by Willem07** [comment]
It was easy, it seems version 1.19-1.19.4 does not work in version 1.19.2, because I see that cloth config 10.096+ is required, but the latest version of cloth config for 1.19.2 is version 8.2.88-forge

**Comment by PieKing1215** [comment]
Oh, I'm not sure why Modrinth is saying 10.0.96+ is required, it's supposed to be set to just require any version.
It seems to work fine for me with 8.2.88, and I'll look into why Modrinth is listing a wrong version.

**Comment by Willem07** [comment]
> О, я не уверен, почему Modrinth говорит, что требуется 10.0.96+, предполагается, что для него требуется только любая версия. Кажется, у меня все нормально работает с 8.2.88, и я разберусь, почему Modrinth указывает неправильную версию.

OK, but my version 0.8.3 doesn't want to work on version 1.19.2-forge-43.2.8 without mods

**Comment by PieKing1215** [comment]
Oh wait that's weird, seems like the mappings in the release jars are all wrong. Maybe I uploaded the wrong jars?
Does the version at the bottom here work? <https://github.com/PieKing1215/InvMove/actions/runs/4432039559>

**Comment by Willem07** [comment]
Yes, it works!

**Comment by PieKing1215** [comment]
Great! I'll upload the correct version to Modrinth in a bit then
