### ISSUE TITLE
Anvil shift

### ISSUE THREAD

**Issue by GalaxysWithFiles** [PieKing1215/InvMove#3]
Describe the bug
Whenever you shift click an item into a anvil it makes you shift for a second no matter what (only does it in the 1st slot for some reason)

To Reproduce
Open anvil then shift click an item

Version and Mod List
List the version of InvMove, the version of Fabric Loader+API, and the version of Minecraft the issue happens on:
InvMove: 0.1.1
Fabric Loader: (dont feel like checking sorry)
Fabric API: 0.46
Minecraft: 1.18.1

**Comment by PieKing1215** [comment]
Fixed for next release (sneak handling is somewhat overhauled as well)
