### ISSUE TITLE
Boat-sprint glitch stops working when inventory opens

### ISSUE THREAD

**Issue by nullifier-exe** [PieKing1215/InvMove#31]
**Describe the bug**
Opening the inventory causes the player to return to normal walking when the player is using a boat-sprint glitch.

**To Reproduce**
boat-sprint glitch is caused when the player paddles faster (pressing ctrl to sprint) while using a boat, then dismounting from it (by pressing shift). this causes the player to sprint as usual, however it doesn't consume hunger as normal sprint would. the glitch is active until the player presses the run key or tries to run by double tapping again.

by opening the inventory the glitch is reset. this happens with any of the options in the config.

**Version and Mod List**
InvMove: InvMove-1.18-0.6.0
Forge/Fabric/Quilt version: 40.0.22
Minecraft: 1.18.2

List any other mods being used: None which interacts with UI or movement

huge sorry if the problem is solved in earlier versions. didn't see the issue submitted though.

**Comment by PieKing1215** [comment]
Seems like this was fixed in vanilla at some point
But I checked on 1.18 with InvMove 0.8.4 and AppleSkin and the glitch worked so I guess some InvMove update made it work
(Also note that the sprint-hit hunger glitch still works with InvMove even in 1.21.1)
