### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by verixyt3** [PieKing1215/InvMove#39]
1.20.2 please

**Comment by PieKing1215** [comment]
Have you tried the [1.20.1 version](https://modrinth.com/mod/invmove/versions?g=1.20.1) yet? I haven't had time to check but it might still work on 1.20.2

**Comment by MendingNights** [comment]
> Have you tried the [1.20.1 version](https://modrinth.com/mod/invmove/versions?g=1.20.1) yet? I haven't had time to check but it might still work on 1.20.2

Nope, it doesn't.

**Comment by PCdudeee** [comment]
@PieKing1215 please 1.20.2 :(

**Comment by PieKing1215** [comment]
(duplicate of gh-40)

Released an update yesterday for 1.20.2+ (v0.8.5):
[GitHub](https://github.com/PieKing1215/InvMove/releases/tag/v0.8.5)
[Modrinth](https://modrinth.com/mod/invmove/changelog?g=1.20.4)

I lightly tested Fabric/Forge on 1.20.2 & 1.20.4 and seemed to be working but lmk if there's any issues
