### ISSUE TITLE
[option] disable the darkened background in inventories that *do* pause the game

### ISSUE THREAD

**Issue by yesn0t** [PieKing1215/InvMove#4]
hi, thank you very much for making this mod !

**Describe the feature you'd like**
an option to disable the darkened background in inventories that pause the game

**Is your feature request related to a problem? Please describe.**
i would like to have a consistent brightness while playing minecraft, and the darkened background gets in the way... 
Specifically, when combined with [Inventory Pause](https://modrinth.com/mod/inventory-pause-cursed), it makes the player inventory have a darkened background again, due to the pausing.
In the pause screen, all the buttons are already encased in solid grey background, so the dark tink doesn't help visibility any more than that

**Comment by PieKing1215** [comment]
Added an option for the next release (this rewrite is 1.18 only right now but I might backport some features later)

**Comment by yesn0t** [comment]
awesome, thank you !
i'll try it on 1.17 with dep overrides and see what happens, as my pc can't handle 1.18 very well x)
