### ISSUE TITLE
1.20.2 version pls

### ISSUE THREAD

**Issue by Mariolazer1** [PieKing1215/InvMove#40]
Update the mod to 1.20.2 pls its an amazing mod

**Comment by PieKing1215** [comment]
Have you tried the [1.20.1 version](https://modrinth.com/mod/invmove/versions?g=1.20.1) yet? I haven't had time to check but it might still work on 1.20.2

**Comment by Mariolazer1** [comment]
yes i tried and had a lot of errors on fabric loader with a copple mods it gave me a exit code 1 (dont know if that matters)

**Comment by megabyte6** [comment]
Minecraft 1.20.2 just doesn't start for me. I tried creating a new instance with fabric 0.14.23, fabric API 0.90.0, and cloth config API 12.0.109. All of those should be the latest version as of today.

**Comment by MendingNights** [comment]
> Have you tried the [1.20.1 version](https://modrinth.com/mod/invmove/versions?g=1.20.1) yet? I haven't had time to check but it might still work on 1.20.2

1.20.2 crashes on startup with the 1.20.1 version of InvMove installed.

**Comment by SoulxluoS** [comment]
[PieKing1215](https://github.com/PieKing1215/PieKing1215) Thank you for good mod.

It's just a working temporary version 1.20.2 FOR FABRIC.
https://github.com/YoungSoulluoS/InvMoveFork/releases/download/1.20.2/InvMove-0.8.4.jar

**Comment by venaminecraft** [comment]
Thank you for the updated version @YoungSoulluoS 😄

**Comment by megabyte6** [comment]
@YoungSoulluoS I was just wondering, how did you fix the issue?

**Comment by PieKing1215** [comment]
btw yeah sorry I haven't updated this in a while, I'm working full time now and updating this is still kinda annoying even with a good amount of the code shared between versions/mod loaders (I also haven't really played mc yet since 1.20 which is normally what forces me to update)
I have a break coming up so I should have some time to get this fully up to date, then in the future I want to do more research into how other mods do crossversion/crossloader support to try to find an easier way

**Comment by megabyte6** [comment]
That sounds fantastic!

The only thing I can think of that has cross-loader support is [architectury](https://modrinth.com/mod/architectury-api).

**Comment by PieKing1215** [comment]
Ok finally got around to updating for 1.20.2-4!
[GitHub](https://github.com/PieKing1215/InvMove/releases/tag/v0.8.5)
[Modrinth](https://modrinth.com/mod/invmove/changelog?g=1.20.4)

I lightly tested Fabric/Forge on 1.20.2 & 1.20.4 and seemed to be working but lmk if there's any issues
