### ISSUE TITLE
toggle crouch glitch

### ISSUE THREAD

**Issue by ChocoMartini** [PieKing1215/InvMove#5]
when I open inventory while crouching using toggle crouch it cause repeating crouch and stand in maintain mode
edit1 : I used v0.6.1(fabric) of this mod

**Comment by PieKing1215** [comment]
Thanks for the report, I forgot they added toggle crouch so I never tested it. I'll look into fixing this for the next version

**Comment by PieKing1215** [comment]
Fixed for next release, will probably release later today or tomorrow!
