### ISSUE TITLE
Compatibility with BuildingGadgets2 questionable

### ISSUE THREAD

**Issue by Barerock** [PieKing1215/InvMove#53]
**Describe the bug**
After decisive testing with over 310 mods, I've discovered that this mod crashes with BuildGadgets2 by Direwolf20 _sometimes_. This is weird and annoying because I played several hours with both installed last night and today, and only after trying to install Computer Craft, and subsequently disabling it due to this, did this bug occur. Now, this bug occurs all the time only on one profile and crashes the game on startup after initialization, reporting that InvMove has a problem in the error context menu that displays when the game crashes.

However. These two mods function fine if alone together, and reading the logs I think it may have to do with InvMove's config, which I've deleted for a quick test after I report this. I even took direct copies of the mod files from the crashing profile and readded them 165, then 25 at a time until complete with no startup crashes related to InvMove.

**To Reproduce**
For my profile, I can install BG2 and InvMove, simply removing the BG2 file then readding it between tests, and it will crash with BG2 and InvMove and it will not crash without BG2 and InvMove. Other profiles will not have this issue.

**Crash Log**
[crash-2024-07-15_17.14.39-fml.txt](https://github.com/user-attachments/files/16240408/crash-2024-07-15_17.14.39-fml.txt)
[latest.log](https://github.com/user-attachments/files/16240412/latest.log)

**Version and Mod List**
List the version of InvMove, the version of Forge/Fabric/Quilt, and the version of Minecraft the issue happens on:
InvMove: 1.20-0.8.4-Forge
Forge/Fabric/Quilt version: Forge 47.2.20
Minecraft: 1.20.1

List any other mods being used: 
[A-ModList.txt](https://github.com/user-attachments/files/16240447/A-ModList.txt)

If possible, try to reproduce the bug with the smallest number of other mods you can. This can help me figure out where the problem occurs.
However, if the issue is truly a compatibility problem with another mod, I will likely be able to fix it if you include the mod list.
^ as explained above, I couldn't, and this _only_ occurs with InvMove. These are non-ideal circumstances for a mod incompatibility.

**Comment by Barerock** [comment]
Crash occurred identically with new config generated

**Comment by Barerock** [comment]
[latest.log](https://github.com/user-attachments/files/16240550/latest.log)
Latest log from working profile with identical configs and mod files (copied directly).

**Comment by Barerock** [comment]
I just successfully loaded in the not-crashing profile all the CC mods I added before this issue occurred, plus vs-additions. Both InvMove and BG2 are in as well.

**Comment by PieKing1215** [comment]
Hey!
This should be fixed in InvMove 0.8.8+ (issue on my side where the unrecognized screens loading could cause other mods' code to run early if they use a certain setup)
Currently that version is only out for 1.21 but I will backport it eventually

For now, based on the crash log I would expect if you go in InvMove's unrecognized.json (in the crashing profile) there should be a line like `"com.direwolf20.buildinggadgets2.client.screen.TemplateManagerGUI": true,`? If you remove that line it should stop crashing (unless there's other ones that crash too).
But annoyingly when you view that screen ingame again it'll readd that line and crash on future startups until you remove it again

**Comment by Barerock** [comment]
Where is that .json located?

**Comment by PieKing1215** [comment]
Oh should be in .minecraft(or equivalent)/config/invmove/unrecognized.json

**Comment by Barerock** [comment]
Nope. Doesn't exist. I looked friggin everywhere too. This is a problem with connector not making fabric mods load their configs. Will generating one in a fabric profile and just copying it over work? (I'm gonna do it anyway to see).

**Comment by Barerock** [comment]
nvm I'm just _blind_ and assumed it did what another mod did. OOPS, thanks, G

**Comment by Barerock** [comment]
oh ffs now make bubbles pop is breaking

**Comment by Barerock** [comment]
_shrug_ it all works now on my main profile. I guess prism is just janky. Thanks, <3 to you and Direwolf20 who will eventually maybe see this lol. Absolutely gorgeous mods!

**Comment by Barerock** [comment]
This is now actually resolved. My mod manager did some gymnastics and so the last test was false. I confirmed FINALLY that removing all of those lines (2) works. 

Thanks. My goodness it's been a hassle here today.
