### ISSUE TITLE
[Feature] Add config value to make unrecognized UI's set to "Disallow Movement" by default

### ISSUE THREAD

**Issue by ChristopherHaws** [PieKing1215/InvMove#6]
I use a lot of mods that have custom UI and would love to be able to have the movement value be "Disallow Movement" by default for unrecognized UI's. For the very few UI's that I want to allow movement, I would go in an manually enable it.

Some mods I use with custom UI:
- Litematica
- MiniHUD
- Tweakaroo
- Xaero's World Map

In all of these cases, I want movement to be disabled. The problem is, each of these mods have many submenus that I have to go and disallow movement manually, and I can only do it after opening the screen for the first time.

**Comment by PieKing1215** [comment]
Good suggestion! Not sure why I didn't do this in the first place, will be in the next release.

**Comment by PieKing1215** [comment]
Added in [v0.7.0](https://github.com/PieKing1215/InvMove/releases/tag/v0.7.0)!
