### ISSUE TITLE
mod somehow not compatible with sodium 

### ISSUE THREAD

**Issue by rinkeChillow** [PieKing1215/InvMove#60]
when in modset that have sodium mod prevents the game from starting 
`java.lang.RuntimeException: Could not execute entrypoint`

when invmove and sodium are in the same pack the game dose not start 
 when its only invmove game starts as normal when its only sodium game also starts as normal  

here is the crash log 
https://mclo.gs/qQZAmvM

InvMove: 1.21-0.8.8-fabric
Fabric version: 0.16.x (tried them all 0 to 3 )
Minecraft: 1.21

so we all know this is a compatibility issue so here is all my mods 
[Uploading bruh-5.0.PieKing for PieKing1215.zip…]()
this file has to be in an .mrpack format so change it to that and use modrinth app

**Comment by PieKing1215** [comment]
If you go in `.minecraft/config/invmove/unrecognized.json` and search for "ScreenPromptable", does removing those lines fix it?

**Comment by rinkeChillow** [comment]
yes it did

**Comment by PieKing1215** [comment]
Ok nice, could be something unusual with how that screen is set up in Sodium, `NoClassDefFoundError` basically means when my config code tried to load it, it didn't exist
It's supposed to handle that and just ignore the error but I only checked for `ClassNotFoundException` but not `NoClassDefFoundError`

I'll see if I can make a quick update soon, but for now removing the broken entries from `unrecognized.json` is the best solution :)

**Comment by rinkeChillow** [comment]
keep the good work man
