### ISSUE TITLE
Compatibility issue with mod JEI

### ISSUE THREAD

**Issue by MagicHead333** [PieKing1215/InvMove#63]
Issue: Player moves when typing with WASD in the mod JEI's search bar.

It would be nice if this mod could be compatible with JEI. When you have a lot of mods and you have to spend some time searching for recipes it gets quite annoying seeing your character fiddle around while you type.

I'm on Minecraft version 1.20.1 Mod version 0.8.4

**Comment by PieKing1215** [comment]
https://modrinth.com/mod/invmovecompats :)

**Comment by MagicHead333** [comment]
Damn it's not for Minecraft version 1.20.1 :(

**Comment by PieKing1215** [comment]
No there's versions for 1.20.1: https://modrinth.com/mod/invmovecompats/versions?g=1.20.1 (unless it doesn't work for some reason)

**Comment by MagicHead333** [comment]
Oh cool. On curseforge its only up to 1.18.2. That's y I thought it wasn't for 1.20.1. Thanks g

**Comment by Allomere** [comment]
1.19.2? 😞
